global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
  - "django.rules"

scrape_configs:
  - job_name: 'django'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8000']
      # Mac host-name
      # - targets: ['docker.for.mac.localhost:8000']
